---
name: V2G Liberty
version: 0.4.1
slug: v2g-liberty
description: The V2G Liberty add-on delivers full automatic and optimised control over Vehicle to Grid (V2G) / bidirectional charging of your electric vehicle.
url: https://github.com/V2G-liberty/addon-v2g-liberty
arch:
  - aarch64
  - amd64
  - armv7
init: false
homeassistant_api: true
uart: true
map:
  - addon_config:rw
  - homeassistant_config:rw
  - ssl
